summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: true
        fullHeight: false
        h: 2
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: true
        fullHeight: false
        h: 2
        w: 6
        x: 0
        'y': 0
      id: topbar
      data:
        id: topbar
        type: containercomponent
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 2
        w: 12
        x: 0
        'y': 3
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 12
        x: 0
        'y': 10
      id: b
      data:
        id: b
        type: navbarcomponent
        configuration:
          borderColor:
            type: static
            value: '#555'
          logo:
            type: oneOf
            configuration:
              'no': {}
              'yes':
                altText:
                  type: static
                  value: ''
                source:
                  type: static
                  value: /logo.svg
                sourceKind:
                  type: static
                  value: url
            selected: 'no'
          orientation:
            type: static
            value: horizontal
            connections: []
            expr: '"horizontal"'
          title:
            type: static
            value: Title
        customCss:
          container:
            class: ''
            style: ''
          image:
            class: ''
            style: ''
        horizontalAlignment: center
        navbarItems: []
        verticalAlignment: center
    - '12':
        fixed: false
        fullHeight: false
        h: 8
        w: 6
        x: 0
        'y': 5
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 2
        x: 0
        'y': 2
      id: a
      data:
        id: a
        type: verticalsplitpanescomponent
        configuration: {}
        customCss:
          container:
            class: ''
            style: ''
        numberOfSubgrids: 2
        panes:
          - 50
          - 50
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 2
        x: 6
        'y': 8
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 1
        x: 2
        'y': 2
      id: c
      data:
        id: c
        type: buttoncomponent
        componentInput:
          type: runnable
          fields: {}
          fieldType: any
        configuration:
          afterIcon:
            type: static
          beforeIcon:
            type: static
          color:
            type: static
            value: blue
          confirmationModal:
            type: oneOf
            configuration:
              confirmationModal:
                description:
                  type: static
                  value: Are you sure?
                confirmationText:
                  type: static
                  value: Confirm
                title:
                  type: static
                  value: Title
              none: {}
            selected: none
          disabled:
            type: static
            value: false
          fillContainer:
            type: static
            value: false
          label:
            type: static
            value: Press me
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: An error occured
              setTab:
                setTab:
                  type: static
                  value: []
            selected: errorOverlay
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: none
          size:
            type: static
            value: xs
          triggerOnAppLoad:
            type: static
            value: false
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
        verticalAlignment: center
  hiddenInlineScripts:
    - type: runnableByName
      name: Background Runnable 0
      autoRefresh: true
      fields:
        u:
          type: static
          value: '$res:u/admin/transparent_postgresql'
          fieldType: object
          format: resource-postgresql
        x:
          type: static
          value: ''
          connections: []
          fieldType: string
      inlineScript:
        content: '!inline background_runnable_0.inline_script.ts'
        lock: '!inline background_runnable_0.inline_script.lock'
        language: bun
        path: u/admin/newapp/Background_Runnable_0
        schema:
          $schema: 'https://json-schema.org/draft/2020-12/schema'
          type: object
          properties:
            u:
              type: object
              description: ''
              default: null
              format: resource-postgresql
            x:
              type: string
              description: ''
              default: null
              originalType: string
          required:
            - x
            - u
      recomputeIds: []
      recomputeOnInputChanged: true
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    a-0: []
    a-1: []
    topbar-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        id: title
        data:
          id: title
          type: textcomponent
          componentInput:
            type: templatev2
            connections:
              - id: summary
                componentId: ctx
            eval: '${ctx.summary}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 6
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          'y': 1
        id: recomputeall
        data:
          id: recomputeall
          type: recomputeallcomponent
          configuration:
            defaultRefreshInterval:
              type: static
              value: '0'
          customCss:
            container:
              class: ''
              style: ''
          horizontalAlignment: right
          menuItems: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  allowed_s3_keys: []
  execution_mode: publisher
  s3_inputs: []
  triggerables_v2:
    'bg_0:rawscript/41073b8d288ef1ea3443cf5d29a0d0a90da6a1941e1664198a35079d9a8eecb4':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs:
        u: '$res:u/admin/transparent_postgresql'
        x: ''
