name: Windmill Ephemeral workspaces sync

on:
  push:
    branches:
      - 'wm-ephemeral/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Windmill CLI
        run: npm install -g windmill-cli

      - name: Extract workspace from branch name
        id: workspace
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          WORKSPACE=$(echo "$BRANCH_NAME" | sed 's|wm-ephemeral/|wm-ephemeral-|' | sed 's|/|-|g')
          echo "workspace=$WORKSPACE" >> $GITHUB_OUTPUT

      - name: Add the Windmill workspace to CLI
        run: |
          wmill workspace add ${{ steps.workspace.outputs.workspace }} --token ${{ secrets.WMILL_TOKEN }} --base-url ${{ secrets.WMILL_BASE_URL }}
          wmill workspace switch ${{ steps.workspace.outputs.workspace }}

      - name: Sync to Windmill
        run: wmill sync push
